# Repository Configuration for /report command
# This file defines repositories available for issue creation

# Core repositories (maintained in prompts repository)
core:
  - name: prompts
    owner: aRustyDev
    description: "Slash command system and Claude configuration"
    templates: issues-prompts
    default_assignee: "@me"
    
  - name: dotfiles
    owner: aRustyDev
    description: "Personal dotfiles and system configuration"
    templates: issues-dotfiles
    default_assignee: "@me"
    
  - name: pre-commit-hooks
    owner: aRustyDev
    description: "Custom pre-commit hooks collection"
    templates: issues-pre-commit-hooks
    default_assignee: "@me"

# Custom repositories (add your own here)
# These will use templates from issues-custom/ directory
custom: []
  # Example:
  # - name: my-project
  #   owner: myusername
  #   description: "My awesome project"
  #   templates: issues-custom
  #   default_assignee: "@me"